name: delight
description: Delight - music everywhere!

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^8.3.0
  flutter_audio_query: ^0.3.5+6
  provider: ^6.0.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
